#Log level
log_level = "info"
elastic_address = "localhost"
elastic_port = 9200
elastic_index = "quiz_registrator_api_prod"
elastic_logs_enabled = true

#
# Reminder settings
#
rabbitmq_address = "localhost"
rabbitmq_port = 5672
rabbitmq_game_reminder_queue_name = "quiz_game_reminder_prod"
rabbitmq_lottery_reminder_queue_name = "quiz_lottery_reminder_prod"
rabbitmq_username = "quiz_reminder"

#
# Telegram Bot settings
#
games_with_photos_list_limit = 8
group_id = -826325866
registrator_api_address = "localhost"
registrator_api_port = 8080
telegram_api_bind_address = "localhost"
telegram_api_bind_port = 8081
