version: "3.9"

services:
  telegram:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_PATH: https://github.com/nikita5637/quiz-telegram.git
        BRANCH: v1.0
    command: "/bin/telegram --config /etc/config.yaml"
    container_name: telegram
    environment:
    networks:
      - network
    ports:
      - "8081:8081"

networks:
  network:
    driver: bridge