package model

// PaymentType ...
type PaymentType int32

const (
	// PaymentTypeInvalid ...
	PaymentTypeInvalid PaymentType = iota
	// PaymentTypeCash ...
	PaymentTypeCash
	// PaymentTypeCertificate ...
	PaymentTypeCertificate
	// PaymentTypeMixed ...
	PaymentTypeMixed
)
