package model

// UserState ...
type UserState byte

const (
	// UserStateUnknown ...
	UserStateUnknown UserState = iota
	// UserStateWelcome ...
	UserStateWelcome
	// UserStateRegistered ...
	UserStateRegistered
	// UserStateChangingEmail ...
	UserStateChangingEmail
	// UserStateChangingName ...
	UserStateChangingName
	// UserStateChangingPhone ...
	UserStateChangingPhone
	// UserStateBanned ...
	UserStateBanned
	// ...

	// UserStatesNumber ...
	UserStatesNumber
)
