// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	certificatemanager "github.com/nikita5637/quiz-registrator-api/pkg/pb/certificate_manager"

	context "context"

	emptypb "google.golang.org/protobuf/types/known/emptypb"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// CertificateManagerServiceClient is an autogenerated mock type for the CertificateManagerServiceClient type
type CertificateManagerServiceClient struct {
	mock.Mock
}

type CertificateManagerServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *CertificateManagerServiceClient) EXPECT() *CertificateManagerServiceClient_Expecter {
	return &CertificateManagerServiceClient_Expecter{mock: &_m.Mock}
}

// ListCertificates provides a mock function with given fields: ctx, in, opts
func (_m *CertificateManagerServiceClient) ListCertificates(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*certificatemanager.ListCertificatesResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *certificatemanager.ListCertificatesResponse
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) *certificatemanager.ListCertificatesResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*certificatemanager.ListCertificatesResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CertificateManagerServiceClient_ListCertificates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCertificates'
type CertificateManagerServiceClient_ListCertificates_Call struct {
	*mock.Call
}

// ListCertificates is a helper method to define mock.On call
//  - ctx context.Context
//  - in *emptypb.Empty
//  - opts ...grpc.CallOption
func (_e *CertificateManagerServiceClient_Expecter) ListCertificates(ctx interface{}, in interface{}, opts ...interface{}) *CertificateManagerServiceClient_ListCertificates_Call {
	return &CertificateManagerServiceClient_ListCertificates_Call{Call: _e.mock.On("ListCertificates",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *CertificateManagerServiceClient_ListCertificates_Call) Run(run func(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption)) *CertificateManagerServiceClient_ListCertificates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*emptypb.Empty), variadicArgs...)
	})
	return _c
}

func (_c *CertificateManagerServiceClient_ListCertificates_Call) Return(_a0 *certificatemanager.ListCertificatesResponse, _a1 error) *CertificateManagerServiceClient_ListCertificates_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewCertificateManagerServiceClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewCertificateManagerServiceClient creates a new instance of CertificateManagerServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCertificateManagerServiceClient(t mockConstructorTestingTNewCertificateManagerServiceClient) *CertificateManagerServiceClient {
	mock := &CertificateManagerServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
