// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	game "github.com/nikita5637/quiz-registrator-api/pkg/pb/game"
	emptypb "google.golang.org/protobuf/types/known/emptypb"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// GameServiceClient is an autogenerated mock type for the GameServiceClient type
type GameServiceClient struct {
	mock.Mock
}

type GameServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *GameServiceClient) EXPECT() *GameServiceClient_Expecter {
	return &GameServiceClient_Expecter{mock: &_m.Mock}
}

// BatchGetGames provides a mock function with given fields: ctx, in, opts
func (_m *GameServiceClient) BatchGetGames(ctx context.Context, in *game.BatchGetGamesRequest, opts ...grpc.CallOption) (*game.BatchGetGamesResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *game.BatchGetGamesResponse
	if rf, ok := ret.Get(0).(func(context.Context, *game.BatchGetGamesRequest, ...grpc.CallOption) *game.BatchGetGamesResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*game.BatchGetGamesResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *game.BatchGetGamesRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GameServiceClient_BatchGetGames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchGetGames'
type GameServiceClient_BatchGetGames_Call struct {
	*mock.Call
}

// BatchGetGames is a helper method to define mock.On call
//  - ctx context.Context
//  - in *game.BatchGetGamesRequest
//  - opts ...grpc.CallOption
func (_e *GameServiceClient_Expecter) BatchGetGames(ctx interface{}, in interface{}, opts ...interface{}) *GameServiceClient_BatchGetGames_Call {
	return &GameServiceClient_BatchGetGames_Call{Call: _e.mock.On("BatchGetGames",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *GameServiceClient_BatchGetGames_Call) Run(run func(ctx context.Context, in *game.BatchGetGamesRequest, opts ...grpc.CallOption)) *GameServiceClient_BatchGetGames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*game.BatchGetGamesRequest), variadicArgs...)
	})
	return _c
}

func (_c *GameServiceClient_BatchGetGames_Call) Return(_a0 *game.BatchGetGamesResponse, _a1 error) *GameServiceClient_BatchGetGames_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetGame provides a mock function with given fields: ctx, in, opts
func (_m *GameServiceClient) GetGame(ctx context.Context, in *game.GetGameRequest, opts ...grpc.CallOption) (*game.Game, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *game.Game
	if rf, ok := ret.Get(0).(func(context.Context, *game.GetGameRequest, ...grpc.CallOption) *game.Game); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*game.Game)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *game.GetGameRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GameServiceClient_GetGame_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGame'
type GameServiceClient_GetGame_Call struct {
	*mock.Call
}

// GetGame is a helper method to define mock.On call
//  - ctx context.Context
//  - in *game.GetGameRequest
//  - opts ...grpc.CallOption
func (_e *GameServiceClient_Expecter) GetGame(ctx interface{}, in interface{}, opts ...interface{}) *GameServiceClient_GetGame_Call {
	return &GameServiceClient_GetGame_Call{Call: _e.mock.On("GetGame",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *GameServiceClient_GetGame_Call) Run(run func(ctx context.Context, in *game.GetGameRequest, opts ...grpc.CallOption)) *GameServiceClient_GetGame_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*game.GetGameRequest), variadicArgs...)
	})
	return _c
}

func (_c *GameServiceClient_GetGame_Call) Return(_a0 *game.Game, _a1 error) *GameServiceClient_GetGame_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// ListGames provides a mock function with given fields: ctx, in, opts
func (_m *GameServiceClient) ListGames(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*game.ListGamesResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *game.ListGamesResponse
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) *game.ListGamesResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*game.ListGamesResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GameServiceClient_ListGames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListGames'
type GameServiceClient_ListGames_Call struct {
	*mock.Call
}

// ListGames is a helper method to define mock.On call
//  - ctx context.Context
//  - in *emptypb.Empty
//  - opts ...grpc.CallOption
func (_e *GameServiceClient_Expecter) ListGames(ctx interface{}, in interface{}, opts ...interface{}) *GameServiceClient_ListGames_Call {
	return &GameServiceClient_ListGames_Call{Call: _e.mock.On("ListGames",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *GameServiceClient_ListGames_Call) Run(run func(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption)) *GameServiceClient_ListGames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*emptypb.Empty), variadicArgs...)
	})
	return _c
}

func (_c *GameServiceClient_ListGames_Call) Return(_a0 *game.ListGamesResponse, _a1 error) *GameServiceClient_ListGames_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// SearchPassedAndRegisteredGames provides a mock function with given fields: ctx, in, opts
func (_m *GameServiceClient) SearchPassedAndRegisteredGames(ctx context.Context, in *game.SearchPassedAndRegisteredGamesRequest, opts ...grpc.CallOption) (*game.SearchPassedAndRegisteredGamesResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *game.SearchPassedAndRegisteredGamesResponse
	if rf, ok := ret.Get(0).(func(context.Context, *game.SearchPassedAndRegisteredGamesRequest, ...grpc.CallOption) *game.SearchPassedAndRegisteredGamesResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*game.SearchPassedAndRegisteredGamesResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *game.SearchPassedAndRegisteredGamesRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GameServiceClient_SearchPassedAndRegisteredGames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchPassedAndRegisteredGames'
type GameServiceClient_SearchPassedAndRegisteredGames_Call struct {
	*mock.Call
}

// SearchPassedAndRegisteredGames is a helper method to define mock.On call
//  - ctx context.Context
//  - in *game.SearchPassedAndRegisteredGamesRequest
//  - opts ...grpc.CallOption
func (_e *GameServiceClient_Expecter) SearchPassedAndRegisteredGames(ctx interface{}, in interface{}, opts ...interface{}) *GameServiceClient_SearchPassedAndRegisteredGames_Call {
	return &GameServiceClient_SearchPassedAndRegisteredGames_Call{Call: _e.mock.On("SearchPassedAndRegisteredGames",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *GameServiceClient_SearchPassedAndRegisteredGames_Call) Run(run func(ctx context.Context, in *game.SearchPassedAndRegisteredGamesRequest, opts ...grpc.CallOption)) *GameServiceClient_SearchPassedAndRegisteredGames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*game.SearchPassedAndRegisteredGamesRequest), variadicArgs...)
	})
	return _c
}

func (_c *GameServiceClient_SearchPassedAndRegisteredGames_Call) Return(_a0 *game.SearchPassedAndRegisteredGamesResponse, _a1 error) *GameServiceClient_SearchPassedAndRegisteredGames_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewGameServiceClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewGameServiceClient creates a new instance of GameServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGameServiceClient(t mockConstructorTestingTNewGameServiceClient) *GameServiceClient {
	mock := &GameServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
