// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	registrator "github.com/nikita5637/quiz-registrator-api/pkg/pb/registrator"
)

// RegistratorServiceClient is an autogenerated mock type for the RegistratorServiceClient type
type RegistratorServiceClient struct {
	mock.Mock
}

type RegistratorServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *RegistratorServiceClient) EXPECT() *RegistratorServiceClient_Expecter {
	return &RegistratorServiceClient_Expecter{mock: &_m.Mock}
}

// GetGameByID provides a mock function with given fields: ctx, in, opts
func (_m *RegistratorServiceClient) GetGameByID(ctx context.Context, in *registrator.GetGameByIDRequest, opts ...grpc.CallOption) (*registrator.GetGameByIDResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *registrator.GetGameByIDResponse
	if rf, ok := ret.Get(0).(func(context.Context, *registrator.GetGameByIDRequest, ...grpc.CallOption) *registrator.GetGameByIDResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registrator.GetGameByIDResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *registrator.GetGameByIDRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegistratorServiceClient_GetGameByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGameByID'
type RegistratorServiceClient_GetGameByID_Call struct {
	*mock.Call
}

// GetGameByID is a helper method to define mock.On call
//  - ctx context.Context
//  - in *registrator.GetGameByIDRequest
//  - opts ...grpc.CallOption
func (_e *RegistratorServiceClient_Expecter) GetGameByID(ctx interface{}, in interface{}, opts ...interface{}) *RegistratorServiceClient_GetGameByID_Call {
	return &RegistratorServiceClient_GetGameByID_Call{Call: _e.mock.On("GetGameByID",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *RegistratorServiceClient_GetGameByID_Call) Run(run func(ctx context.Context, in *registrator.GetGameByIDRequest, opts ...grpc.CallOption)) *RegistratorServiceClient_GetGameByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*registrator.GetGameByIDRequest), variadicArgs...)
	})
	return _c
}

func (_c *RegistratorServiceClient_GetGameByID_Call) Return(_a0 *registrator.GetGameByIDResponse, _a1 error) *RegistratorServiceClient_GetGameByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetGames provides a mock function with given fields: ctx, in, opts
func (_m *RegistratorServiceClient) GetGames(ctx context.Context, in *registrator.GetGamesRequest, opts ...grpc.CallOption) (*registrator.GetGamesResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *registrator.GetGamesResponse
	if rf, ok := ret.Get(0).(func(context.Context, *registrator.GetGamesRequest, ...grpc.CallOption) *registrator.GetGamesResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registrator.GetGamesResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *registrator.GetGamesRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegistratorServiceClient_GetGames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGames'
type RegistratorServiceClient_GetGames_Call struct {
	*mock.Call
}

// GetGames is a helper method to define mock.On call
//  - ctx context.Context
//  - in *registrator.GetGamesRequest
//  - opts ...grpc.CallOption
func (_e *RegistratorServiceClient_Expecter) GetGames(ctx interface{}, in interface{}, opts ...interface{}) *RegistratorServiceClient_GetGames_Call {
	return &RegistratorServiceClient_GetGames_Call{Call: _e.mock.On("GetGames",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *RegistratorServiceClient_GetGames_Call) Run(run func(ctx context.Context, in *registrator.GetGamesRequest, opts ...grpc.CallOption)) *RegistratorServiceClient_GetGames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*registrator.GetGamesRequest), variadicArgs...)
	})
	return _c
}

func (_c *RegistratorServiceClient_GetGames_Call) Return(_a0 *registrator.GetGamesResponse, _a1 error) *RegistratorServiceClient_GetGames_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetRegisteredGames provides a mock function with given fields: ctx, in, opts
func (_m *RegistratorServiceClient) GetRegisteredGames(ctx context.Context, in *registrator.GetRegisteredGamesRequest, opts ...grpc.CallOption) (*registrator.GetRegisteredGamesResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *registrator.GetRegisteredGamesResponse
	if rf, ok := ret.Get(0).(func(context.Context, *registrator.GetRegisteredGamesRequest, ...grpc.CallOption) *registrator.GetRegisteredGamesResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registrator.GetRegisteredGamesResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *registrator.GetRegisteredGamesRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegistratorServiceClient_GetRegisteredGames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRegisteredGames'
type RegistratorServiceClient_GetRegisteredGames_Call struct {
	*mock.Call
}

// GetRegisteredGames is a helper method to define mock.On call
//  - ctx context.Context
//  - in *registrator.GetRegisteredGamesRequest
//  - opts ...grpc.CallOption
func (_e *RegistratorServiceClient_Expecter) GetRegisteredGames(ctx interface{}, in interface{}, opts ...interface{}) *RegistratorServiceClient_GetRegisteredGames_Call {
	return &RegistratorServiceClient_GetRegisteredGames_Call{Call: _e.mock.On("GetRegisteredGames",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *RegistratorServiceClient_GetRegisteredGames_Call) Run(run func(ctx context.Context, in *registrator.GetRegisteredGamesRequest, opts ...grpc.CallOption)) *RegistratorServiceClient_GetRegisteredGames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*registrator.GetRegisteredGamesRequest), variadicArgs...)
	})
	return _c
}

func (_c *RegistratorServiceClient_GetRegisteredGames_Call) Return(_a0 *registrator.GetRegisteredGamesResponse, _a1 error) *RegistratorServiceClient_GetRegisteredGames_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetUserGames provides a mock function with given fields: ctx, in, opts
func (_m *RegistratorServiceClient) GetUserGames(ctx context.Context, in *registrator.GetUserGamesRequest, opts ...grpc.CallOption) (*registrator.GetUserGamesResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *registrator.GetUserGamesResponse
	if rf, ok := ret.Get(0).(func(context.Context, *registrator.GetUserGamesRequest, ...grpc.CallOption) *registrator.GetUserGamesResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registrator.GetUserGamesResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *registrator.GetUserGamesRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegistratorServiceClient_GetUserGames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserGames'
type RegistratorServiceClient_GetUserGames_Call struct {
	*mock.Call
}

// GetUserGames is a helper method to define mock.On call
//  - ctx context.Context
//  - in *registrator.GetUserGamesRequest
//  - opts ...grpc.CallOption
func (_e *RegistratorServiceClient_Expecter) GetUserGames(ctx interface{}, in interface{}, opts ...interface{}) *RegistratorServiceClient_GetUserGames_Call {
	return &RegistratorServiceClient_GetUserGames_Call{Call: _e.mock.On("GetUserGames",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *RegistratorServiceClient_GetUserGames_Call) Run(run func(ctx context.Context, in *registrator.GetUserGamesRequest, opts ...grpc.CallOption)) *RegistratorServiceClient_GetUserGames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*registrator.GetUserGamesRequest), variadicArgs...)
	})
	return _c
}

func (_c *RegistratorServiceClient_GetUserGames_Call) Return(_a0 *registrator.GetUserGamesResponse, _a1 error) *RegistratorServiceClient_GetUserGames_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// RegisterGame provides a mock function with given fields: ctx, in, opts
func (_m *RegistratorServiceClient) RegisterGame(ctx context.Context, in *registrator.RegisterGameRequest, opts ...grpc.CallOption) (*registrator.RegisterGameResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *registrator.RegisterGameResponse
	if rf, ok := ret.Get(0).(func(context.Context, *registrator.RegisterGameRequest, ...grpc.CallOption) *registrator.RegisterGameResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registrator.RegisterGameResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *registrator.RegisterGameRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegistratorServiceClient_RegisterGame_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterGame'
type RegistratorServiceClient_RegisterGame_Call struct {
	*mock.Call
}

// RegisterGame is a helper method to define mock.On call
//  - ctx context.Context
//  - in *registrator.RegisterGameRequest
//  - opts ...grpc.CallOption
func (_e *RegistratorServiceClient_Expecter) RegisterGame(ctx interface{}, in interface{}, opts ...interface{}) *RegistratorServiceClient_RegisterGame_Call {
	return &RegistratorServiceClient_RegisterGame_Call{Call: _e.mock.On("RegisterGame",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *RegistratorServiceClient_RegisterGame_Call) Run(run func(ctx context.Context, in *registrator.RegisterGameRequest, opts ...grpc.CallOption)) *RegistratorServiceClient_RegisterGame_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*registrator.RegisterGameRequest), variadicArgs...)
	})
	return _c
}

func (_c *RegistratorServiceClient_RegisterGame_Call) Return(_a0 *registrator.RegisterGameResponse, _a1 error) *RegistratorServiceClient_RegisterGame_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// UnregisterGame provides a mock function with given fields: ctx, in, opts
func (_m *RegistratorServiceClient) UnregisterGame(ctx context.Context, in *registrator.UnregisterGameRequest, opts ...grpc.CallOption) (*registrator.UnregisterGameResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *registrator.UnregisterGameResponse
	if rf, ok := ret.Get(0).(func(context.Context, *registrator.UnregisterGameRequest, ...grpc.CallOption) *registrator.UnregisterGameResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registrator.UnregisterGameResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *registrator.UnregisterGameRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegistratorServiceClient_UnregisterGame_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnregisterGame'
type RegistratorServiceClient_UnregisterGame_Call struct {
	*mock.Call
}

// UnregisterGame is a helper method to define mock.On call
//  - ctx context.Context
//  - in *registrator.UnregisterGameRequest
//  - opts ...grpc.CallOption
func (_e *RegistratorServiceClient_Expecter) UnregisterGame(ctx interface{}, in interface{}, opts ...interface{}) *RegistratorServiceClient_UnregisterGame_Call {
	return &RegistratorServiceClient_UnregisterGame_Call{Call: _e.mock.On("UnregisterGame",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *RegistratorServiceClient_UnregisterGame_Call) Run(run func(ctx context.Context, in *registrator.UnregisterGameRequest, opts ...grpc.CallOption)) *RegistratorServiceClient_UnregisterGame_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*registrator.UnregisterGameRequest), variadicArgs...)
	})
	return _c
}

func (_c *RegistratorServiceClient_UnregisterGame_Call) Return(_a0 *registrator.UnregisterGameResponse, _a1 error) *RegistratorServiceClient_UnregisterGame_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// UpdatePayment provides a mock function with given fields: ctx, in, opts
func (_m *RegistratorServiceClient) UpdatePayment(ctx context.Context, in *registrator.UpdatePaymentRequest, opts ...grpc.CallOption) (*registrator.UpdatePaymentResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *registrator.UpdatePaymentResponse
	if rf, ok := ret.Get(0).(func(context.Context, *registrator.UpdatePaymentRequest, ...grpc.CallOption) *registrator.UpdatePaymentResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registrator.UpdatePaymentResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *registrator.UpdatePaymentRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegistratorServiceClient_UpdatePayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePayment'
type RegistratorServiceClient_UpdatePayment_Call struct {
	*mock.Call
}

// UpdatePayment is a helper method to define mock.On call
//  - ctx context.Context
//  - in *registrator.UpdatePaymentRequest
//  - opts ...grpc.CallOption
func (_e *RegistratorServiceClient_Expecter) UpdatePayment(ctx interface{}, in interface{}, opts ...interface{}) *RegistratorServiceClient_UpdatePayment_Call {
	return &RegistratorServiceClient_UpdatePayment_Call{Call: _e.mock.On("UpdatePayment",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *RegistratorServiceClient_UpdatePayment_Call) Run(run func(ctx context.Context, in *registrator.UpdatePaymentRequest, opts ...grpc.CallOption)) *RegistratorServiceClient_UpdatePayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*registrator.UpdatePaymentRequest), variadicArgs...)
	})
	return _c
}

func (_c *RegistratorServiceClient_UpdatePayment_Call) Return(_a0 *registrator.UpdatePaymentResponse, _a1 error) *RegistratorServiceClient_UpdatePayment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewRegistratorServiceClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewRegistratorServiceClient creates a new instance of RegistratorServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRegistratorServiceClient(t mockConstructorTestingTNewRegistratorServiceClient) *RegistratorServiceClient {
	mock := &RegistratorServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
