// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mathproblem "github.com/nikita5637/quiz-registrator-api/pkg/pb/math_problem"

	mock "github.com/stretchr/testify/mock"
)

// MathProblemServiceClient is an autogenerated mock type for the MathProblemServiceClient type
type MathProblemServiceClient struct {
	mock.Mock
}

type MathProblemServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MathProblemServiceClient) EXPECT() *MathProblemServiceClient_Expecter {
	return &MathProblemServiceClient_Expecter{mock: &_m.Mock}
}

// SearchMathProblemByGameID provides a mock function with given fields: ctx, in, opts
func (_m *MathProblemServiceClient) SearchMathProblemByGameID(ctx context.Context, in *mathproblem.SearchMathProblemByGameIDRequest, opts ...grpc.CallOption) (*mathproblem.MathProblem, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *mathproblem.MathProblem
	if rf, ok := ret.Get(0).(func(context.Context, *mathproblem.SearchMathProblemByGameIDRequest, ...grpc.CallOption) *mathproblem.MathProblem); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mathproblem.MathProblem)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *mathproblem.SearchMathProblemByGameIDRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MathProblemServiceClient_SearchMathProblemByGameID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchMathProblemByGameID'
type MathProblemServiceClient_SearchMathProblemByGameID_Call struct {
	*mock.Call
}

// SearchMathProblemByGameID is a helper method to define mock.On call
//  - ctx context.Context
//  - in *mathproblem.SearchMathProblemByGameIDRequest
//  - opts ...grpc.CallOption
func (_e *MathProblemServiceClient_Expecter) SearchMathProblemByGameID(ctx interface{}, in interface{}, opts ...interface{}) *MathProblemServiceClient_SearchMathProblemByGameID_Call {
	return &MathProblemServiceClient_SearchMathProblemByGameID_Call{Call: _e.mock.On("SearchMathProblemByGameID",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MathProblemServiceClient_SearchMathProblemByGameID_Call) Run(run func(ctx context.Context, in *mathproblem.SearchMathProblemByGameIDRequest, opts ...grpc.CallOption)) *MathProblemServiceClient_SearchMathProblemByGameID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*mathproblem.SearchMathProblemByGameIDRequest), variadicArgs...)
	})
	return _c
}

func (_c *MathProblemServiceClient_SearchMathProblemByGameID_Call) Return(_a0 *mathproblem.MathProblem, _a1 error) *MathProblemServiceClient_SearchMathProblemByGameID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewMathProblemServiceClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewMathProblemServiceClient creates a new instance of MathProblemServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMathProblemServiceClient(t mockConstructorTestingTNewMathProblemServiceClient) *MathProblemServiceClient {
	mock := &MathProblemServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
