// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	tgbotapi "github.com/go-telegram-bot-api/telegram-bot-api/v5"
	mock "github.com/stretchr/testify/mock"
)

// TelegramBot is an autogenerated mock type for the TelegramBot type
type TelegramBot struct {
	mock.Mock
}

type TelegramBot_Expecter struct {
	mock *mock.Mock
}

func (_m *TelegramBot) EXPECT() *TelegramBot_Expecter {
	return &TelegramBot_Expecter{mock: &_m.Mock}
}

// GetUpdatesChan provides a mock function with given fields: config
func (_m *TelegramBot) GetUpdatesChan(config tgbotapi.UpdateConfig) tgbotapi.UpdatesChannel {
	ret := _m.Called(config)

	var r0 tgbotapi.UpdatesChannel
	if rf, ok := ret.Get(0).(func(tgbotapi.UpdateConfig) tgbotapi.UpdatesChannel); ok {
		r0 = rf(config)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(tgbotapi.UpdatesChannel)
		}
	}

	return r0
}

// TelegramBot_GetUpdatesChan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUpdatesChan'
type TelegramBot_GetUpdatesChan_Call struct {
	*mock.Call
}

// GetUpdatesChan is a helper method to define mock.On call
//  - config tgbotapi.UpdateConfig
func (_e *TelegramBot_Expecter) GetUpdatesChan(config interface{}) *TelegramBot_GetUpdatesChan_Call {
	return &TelegramBot_GetUpdatesChan_Call{Call: _e.mock.On("GetUpdatesChan", config)}
}

func (_c *TelegramBot_GetUpdatesChan_Call) Run(run func(config tgbotapi.UpdateConfig)) *TelegramBot_GetUpdatesChan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(tgbotapi.UpdateConfig))
	})
	return _c
}

func (_c *TelegramBot_GetUpdatesChan_Call) Return(_a0 tgbotapi.UpdatesChannel) *TelegramBot_GetUpdatesChan_Call {
	_c.Call.Return(_a0)
	return _c
}

// Request provides a mock function with given fields: c
func (_m *TelegramBot) Request(c tgbotapi.Chattable) (*tgbotapi.APIResponse, error) {
	ret := _m.Called(c)

	var r0 *tgbotapi.APIResponse
	if rf, ok := ret.Get(0).(func(tgbotapi.Chattable) *tgbotapi.APIResponse); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tgbotapi.APIResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(tgbotapi.Chattable) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TelegramBot_Request_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Request'
type TelegramBot_Request_Call struct {
	*mock.Call
}

// Request is a helper method to define mock.On call
//  - c tgbotapi.Chattable
func (_e *TelegramBot_Expecter) Request(c interface{}) *TelegramBot_Request_Call {
	return &TelegramBot_Request_Call{Call: _e.mock.On("Request", c)}
}

func (_c *TelegramBot_Request_Call) Run(run func(c tgbotapi.Chattable)) *TelegramBot_Request_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(tgbotapi.Chattable))
	})
	return _c
}

func (_c *TelegramBot_Request_Call) Return(_a0 *tgbotapi.APIResponse, _a1 error) *TelegramBot_Request_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// Send provides a mock function with given fields: c
func (_m *TelegramBot) Send(c tgbotapi.Chattable) (tgbotapi.Message, error) {
	ret := _m.Called(c)

	var r0 tgbotapi.Message
	if rf, ok := ret.Get(0).(func(tgbotapi.Chattable) tgbotapi.Message); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Get(0).(tgbotapi.Message)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(tgbotapi.Chattable) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TelegramBot_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type TelegramBot_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//  - c tgbotapi.Chattable
func (_e *TelegramBot_Expecter) Send(c interface{}) *TelegramBot_Send_Call {
	return &TelegramBot_Send_Call{Call: _e.mock.On("Send", c)}
}

func (_c *TelegramBot_Send_Call) Run(run func(c tgbotapi.Chattable)) *TelegramBot_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(tgbotapi.Chattable))
	})
	return _c
}

func (_c *TelegramBot_Send_Call) Return(_a0 tgbotapi.Message, _a1 error) *TelegramBot_Send_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// StopReceivingUpdates provides a mock function with given fields:
func (_m *TelegramBot) StopReceivingUpdates() {
	_m.Called()
}

// TelegramBot_StopReceivingUpdates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopReceivingUpdates'
type TelegramBot_StopReceivingUpdates_Call struct {
	*mock.Call
}

// StopReceivingUpdates is a helper method to define mock.On call
func (_e *TelegramBot_Expecter) StopReceivingUpdates() *TelegramBot_StopReceivingUpdates_Call {
	return &TelegramBot_StopReceivingUpdates_Call{Call: _e.mock.On("StopReceivingUpdates")}
}

func (_c *TelegramBot_StopReceivingUpdates_Call) Run(run func()) *TelegramBot_StopReceivingUpdates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TelegramBot_StopReceivingUpdates_Call) Return() *TelegramBot_StopReceivingUpdates_Call {
	_c.Call.Return()
	return _c
}

type mockConstructorTestingTNewTelegramBot interface {
	mock.TestingT
	Cleanup(func())
}

// NewTelegramBot creates a new instance of TelegramBot. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTelegramBot(t mockConstructorTestingTNewTelegramBot) *TelegramBot {
	mock := &TelegramBot{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
