// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/nikita5637/quiz-telegram/internal/pkg/model"
	mock "github.com/stretchr/testify/mock"
)

// UsersFacade is an autogenerated mock type for the UsersFacade type
type UsersFacade struct {
	mock.Mock
}

type UsersFacade_Expecter struct {
	mock *mock.Mock
}

func (_m *UsersFacade) EXPECT() *UsersFacade_Expecter {
	return &UsersFacade_Expecter{mock: &_m.Mock}
}

// GetUser provides a mock function with given fields: ctx, userID
func (_m *UsersFacade) GetUser(ctx context.Context, userID int32) (model.User, error) {
	ret := _m.Called(ctx, userID)

	var r0 model.User
	if rf, ok := ret.Get(0).(func(context.Context, int32) model.User); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(model.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UsersFacade_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type UsersFacade_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//  - ctx context.Context
//  - userID int32
func (_e *UsersFacade_Expecter) GetUser(ctx interface{}, userID interface{}) *UsersFacade_GetUser_Call {
	return &UsersFacade_GetUser_Call{Call: _e.mock.On("GetUser", ctx, userID)}
}

func (_c *UsersFacade_GetUser_Call) Run(run func(ctx context.Context, userID int32)) *UsersFacade_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *UsersFacade_GetUser_Call) Return(_a0 model.User, _a1 error) *UsersFacade_GetUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// UpdateUserBirthdate provides a mock function with given fields: ctx, userID, birthdate
func (_m *UsersFacade) UpdateUserBirthdate(ctx context.Context, userID int32, birthdate string) error {
	ret := _m.Called(ctx, userID, birthdate)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, string) error); ok {
		r0 = rf(ctx, userID, birthdate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UsersFacade_UpdateUserBirthdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserBirthdate'
type UsersFacade_UpdateUserBirthdate_Call struct {
	*mock.Call
}

// UpdateUserBirthdate is a helper method to define mock.On call
//  - ctx context.Context
//  - userID int32
//  - birthdate string
func (_e *UsersFacade_Expecter) UpdateUserBirthdate(ctx interface{}, userID interface{}, birthdate interface{}) *UsersFacade_UpdateUserBirthdate_Call {
	return &UsersFacade_UpdateUserBirthdate_Call{Call: _e.mock.On("UpdateUserBirthdate", ctx, userID, birthdate)}
}

func (_c *UsersFacade_UpdateUserBirthdate_Call) Run(run func(ctx context.Context, userID int32, birthdate string)) *UsersFacade_UpdateUserBirthdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(string))
	})
	return _c
}

func (_c *UsersFacade_UpdateUserBirthdate_Call) Return(_a0 error) *UsersFacade_UpdateUserBirthdate_Call {
	_c.Call.Return(_a0)
	return _c
}

// UpdateUserEmail provides a mock function with given fields: ctx, userID, email
func (_m *UsersFacade) UpdateUserEmail(ctx context.Context, userID int32, email string) error {
	ret := _m.Called(ctx, userID, email)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, string) error); ok {
		r0 = rf(ctx, userID, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UsersFacade_UpdateUserEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserEmail'
type UsersFacade_UpdateUserEmail_Call struct {
	*mock.Call
}

// UpdateUserEmail is a helper method to define mock.On call
//  - ctx context.Context
//  - userID int32
//  - email string
func (_e *UsersFacade_Expecter) UpdateUserEmail(ctx interface{}, userID interface{}, email interface{}) *UsersFacade_UpdateUserEmail_Call {
	return &UsersFacade_UpdateUserEmail_Call{Call: _e.mock.On("UpdateUserEmail", ctx, userID, email)}
}

func (_c *UsersFacade_UpdateUserEmail_Call) Run(run func(ctx context.Context, userID int32, email string)) *UsersFacade_UpdateUserEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(string))
	})
	return _c
}

func (_c *UsersFacade_UpdateUserEmail_Call) Return(_a0 error) *UsersFacade_UpdateUserEmail_Call {
	_c.Call.Return(_a0)
	return _c
}

// UpdateUserName provides a mock function with given fields: ctx, userID, name
func (_m *UsersFacade) UpdateUserName(ctx context.Context, userID int32, name string) error {
	ret := _m.Called(ctx, userID, name)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, string) error); ok {
		r0 = rf(ctx, userID, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UsersFacade_UpdateUserName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserName'
type UsersFacade_UpdateUserName_Call struct {
	*mock.Call
}

// UpdateUserName is a helper method to define mock.On call
//  - ctx context.Context
//  - userID int32
//  - name string
func (_e *UsersFacade_Expecter) UpdateUserName(ctx interface{}, userID interface{}, name interface{}) *UsersFacade_UpdateUserName_Call {
	return &UsersFacade_UpdateUserName_Call{Call: _e.mock.On("UpdateUserName", ctx, userID, name)}
}

func (_c *UsersFacade_UpdateUserName_Call) Run(run func(ctx context.Context, userID int32, name string)) *UsersFacade_UpdateUserName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(string))
	})
	return _c
}

func (_c *UsersFacade_UpdateUserName_Call) Return(_a0 error) *UsersFacade_UpdateUserName_Call {
	_c.Call.Return(_a0)
	return _c
}

// UpdateUserPhone provides a mock function with given fields: ctx, userID, phone
func (_m *UsersFacade) UpdateUserPhone(ctx context.Context, userID int32, phone string) error {
	ret := _m.Called(ctx, userID, phone)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, string) error); ok {
		r0 = rf(ctx, userID, phone)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UsersFacade_UpdateUserPhone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserPhone'
type UsersFacade_UpdateUserPhone_Call struct {
	*mock.Call
}

// UpdateUserPhone is a helper method to define mock.On call
//  - ctx context.Context
//  - userID int32
//  - phone string
func (_e *UsersFacade_Expecter) UpdateUserPhone(ctx interface{}, userID interface{}, phone interface{}) *UsersFacade_UpdateUserPhone_Call {
	return &UsersFacade_UpdateUserPhone_Call{Call: _e.mock.On("UpdateUserPhone", ctx, userID, phone)}
}

func (_c *UsersFacade_UpdateUserPhone_Call) Run(run func(ctx context.Context, userID int32, phone string)) *UsersFacade_UpdateUserPhone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(string))
	})
	return _c
}

func (_c *UsersFacade_UpdateUserPhone_Call) Return(_a0 error) *UsersFacade_UpdateUserPhone_Call {
	_c.Call.Return(_a0)
	return _c
}

// UpdateUserSex provides a mock function with given fields: ctx, userID, sex
func (_m *UsersFacade) UpdateUserSex(ctx context.Context, userID int32, sex model.Sex) error {
	ret := _m.Called(ctx, userID, sex)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, model.Sex) error); ok {
		r0 = rf(ctx, userID, sex)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UsersFacade_UpdateUserSex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserSex'
type UsersFacade_UpdateUserSex_Call struct {
	*mock.Call
}

// UpdateUserSex is a helper method to define mock.On call
//  - ctx context.Context
//  - userID int32
//  - sex model.Sex
func (_e *UsersFacade_Expecter) UpdateUserSex(ctx interface{}, userID interface{}, sex interface{}) *UsersFacade_UpdateUserSex_Call {
	return &UsersFacade_UpdateUserSex_Call{Call: _e.mock.On("UpdateUserSex", ctx, userID, sex)}
}

func (_c *UsersFacade_UpdateUserSex_Call) Run(run func(ctx context.Context, userID int32, sex model.Sex)) *UsersFacade_UpdateUserSex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(model.Sex))
	})
	return _c
}

func (_c *UsersFacade_UpdateUserSex_Call) Return(_a0 error) *UsersFacade_UpdateUserSex_Call {
	_c.Call.Return(_a0)
	return _c
}

// UpdateUserState provides a mock function with given fields: ctx, userID, state
func (_m *UsersFacade) UpdateUserState(ctx context.Context, userID int32, state int32) error {
	ret := _m.Called(ctx, userID, state)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32) error); ok {
		r0 = rf(ctx, userID, state)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UsersFacade_UpdateUserState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserState'
type UsersFacade_UpdateUserState_Call struct {
	*mock.Call
}

// UpdateUserState is a helper method to define mock.On call
//  - ctx context.Context
//  - userID int32
//  - state int32
func (_e *UsersFacade_Expecter) UpdateUserState(ctx interface{}, userID interface{}, state interface{}) *UsersFacade_UpdateUserState_Call {
	return &UsersFacade_UpdateUserState_Call{Call: _e.mock.On("UpdateUserState", ctx, userID, state)}
}

func (_c *UsersFacade_UpdateUserState_Call) Run(run func(ctx context.Context, userID int32, state int32)) *UsersFacade_UpdateUserState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(int32))
	})
	return _c
}

func (_c *UsersFacade_UpdateUserState_Call) Return(_a0 error) *UsersFacade_UpdateUserState_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewUsersFacade interface {
	mock.TestingT
	Cleanup(func())
}

// NewUsersFacade creates a new instance of UsersFacade. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUsersFacade(t mockConstructorTestingTNewUsersFacade) *UsersFacade {
	mock := &UsersFacade{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
