// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	gameplayer "github.com/nikita5637/quiz-registrator-api/pkg/pb/game_player"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// GamePlayerServiceClient is an autogenerated mock type for the GamePlayerServiceClient type
type GamePlayerServiceClient struct {
	mock.Mock
}

type GamePlayerServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *GamePlayerServiceClient) EXPECT() *GamePlayerServiceClient_Expecter {
	return &GamePlayerServiceClient_Expecter{mock: &_m.Mock}
}

// GetGamePlayersByGameID provides a mock function with given fields: ctx, in, opts
func (_m *GamePlayerServiceClient) GetGamePlayersByGameID(ctx context.Context, in *gameplayer.GetGamePlayersByGameIDRequest, opts ...grpc.CallOption) (*gameplayer.GetGamePlayersByGameIDResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *gameplayer.GetGamePlayersByGameIDResponse
	if rf, ok := ret.Get(0).(func(context.Context, *gameplayer.GetGamePlayersByGameIDRequest, ...grpc.CallOption) *gameplayer.GetGamePlayersByGameIDResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gameplayer.GetGamePlayersByGameIDResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *gameplayer.GetGamePlayersByGameIDRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GamePlayerServiceClient_GetGamePlayersByGameID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGamePlayersByGameID'
type GamePlayerServiceClient_GetGamePlayersByGameID_Call struct {
	*mock.Call
}

// GetGamePlayersByGameID is a helper method to define mock.On call
//  - ctx context.Context
//  - in *gameplayer.GetGamePlayersByGameIDRequest
//  - opts ...grpc.CallOption
func (_e *GamePlayerServiceClient_Expecter) GetGamePlayersByGameID(ctx interface{}, in interface{}, opts ...interface{}) *GamePlayerServiceClient_GetGamePlayersByGameID_Call {
	return &GamePlayerServiceClient_GetGamePlayersByGameID_Call{Call: _e.mock.On("GetGamePlayersByGameID",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *GamePlayerServiceClient_GetGamePlayersByGameID_Call) Run(run func(ctx context.Context, in *gameplayer.GetGamePlayersByGameIDRequest, opts ...grpc.CallOption)) *GamePlayerServiceClient_GetGamePlayersByGameID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*gameplayer.GetGamePlayersByGameIDRequest), variadicArgs...)
	})
	return _c
}

func (_c *GamePlayerServiceClient_GetGamePlayersByGameID_Call) Return(_a0 *gameplayer.GetGamePlayersByGameIDResponse, _a1 error) *GamePlayerServiceClient_GetGamePlayersByGameID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetUserGameIDs provides a mock function with given fields: ctx, in, opts
func (_m *GamePlayerServiceClient) GetUserGameIDs(ctx context.Context, in *gameplayer.GetUserGameIDsRequest, opts ...grpc.CallOption) (*gameplayer.GetUserGameIDsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *gameplayer.GetUserGameIDsResponse
	if rf, ok := ret.Get(0).(func(context.Context, *gameplayer.GetUserGameIDsRequest, ...grpc.CallOption) *gameplayer.GetUserGameIDsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gameplayer.GetUserGameIDsResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *gameplayer.GetUserGameIDsRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GamePlayerServiceClient_GetUserGameIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserGameIDs'
type GamePlayerServiceClient_GetUserGameIDs_Call struct {
	*mock.Call
}

// GetUserGameIDs is a helper method to define mock.On call
//  - ctx context.Context
//  - in *gameplayer.GetUserGameIDsRequest
//  - opts ...grpc.CallOption
func (_e *GamePlayerServiceClient_Expecter) GetUserGameIDs(ctx interface{}, in interface{}, opts ...interface{}) *GamePlayerServiceClient_GetUserGameIDs_Call {
	return &GamePlayerServiceClient_GetUserGameIDs_Call{Call: _e.mock.On("GetUserGameIDs",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *GamePlayerServiceClient_GetUserGameIDs_Call) Run(run func(ctx context.Context, in *gameplayer.GetUserGameIDsRequest, opts ...grpc.CallOption)) *GamePlayerServiceClient_GetUserGameIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*gameplayer.GetUserGameIDsRequest), variadicArgs...)
	})
	return _c
}

func (_c *GamePlayerServiceClient_GetUserGameIDs_Call) Return(_a0 *gameplayer.GetUserGameIDsResponse, _a1 error) *GamePlayerServiceClient_GetUserGameIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewGamePlayerServiceClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewGamePlayerServiceClient creates a new instance of GamePlayerServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGamePlayerServiceClient(t mockConstructorTestingTNewGamePlayerServiceClient) *GamePlayerServiceClient {
	mock := &GamePlayerServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
