package bot

// Command ...
type Command byte

// ADD NEW CONSTS AT THE BOTTOM ...
const (
	// CommandInvalid ...
	CommandInvalid Command = iota
	// CommandGamesList ...
	CommandGamesList
	// CommandGetGame ...
	CommandGetGame
	// CommandRegisterGame ...
	CommandRegisterGame
	// CommandRegisterPlayer ...
	CommandRegisterPlayer
	// CommandUnregisterGame ...
	CommandUnregisterGame
	// CommandUnregisterPlayer ...
	CommandUnregisterPlayer
	// CommandPlayersListByGame ...
	CommandPlayersListByGame
	// CommandGetGamePhotos ...
	CommandGetGamePhotos
	// CommandGetListGamesWithPhotosNextPage ...
	CommandGetListGamesWithPhotosNextPage
	// CommandGetListGamesWithPhotosPrevPage ...
	CommandGetListGamesWithPhotosPrevPage
	// CommandUpdatePayment ...
	CommandUpdatePayment
	// CommandChangeEmail ...
	CommandChangeEmail
	// CommandChangeName ...
	CommandChangeName
	// CommandChangePhone ...
	CommandChangePhone
	// CommandLottery ...
	CommandLottery
	// ...

	// CommandsNumber ...
	CommandsNumber
)

// TelegramRequest ...
type TelegramRequest struct {
	Command Command `json:"command,omitempty"`
	Body    []byte  `json:"body,omitempty"`
}
