// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	photomanager "github.com/nikita5637/quiz-registrator-api/pkg/pb/photo_manager"
)

// PhotographerServiceClient is an autogenerated mock type for the PhotographerServiceClient type
type PhotographerServiceClient struct {
	mock.Mock
}

type PhotographerServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *PhotographerServiceClient) EXPECT() *PhotographerServiceClient_Expecter {
	return &PhotographerServiceClient_Expecter{mock: &_m.Mock}
}

// GetPhotosByGameID provides a mock function with given fields: ctx, in, opts
func (_m *PhotographerServiceClient) GetPhotosByGameID(ctx context.Context, in *photomanager.GetPhotosByGameIDRequest, opts ...grpc.CallOption) (*photomanager.GetPhotosByGameIDResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *photomanager.GetPhotosByGameIDResponse
	if rf, ok := ret.Get(0).(func(context.Context, *photomanager.GetPhotosByGameIDRequest, ...grpc.CallOption) *photomanager.GetPhotosByGameIDResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*photomanager.GetPhotosByGameIDResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *photomanager.GetPhotosByGameIDRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PhotographerServiceClient_GetPhotosByGameID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPhotosByGameID'
type PhotographerServiceClient_GetPhotosByGameID_Call struct {
	*mock.Call
}

// GetPhotosByGameID is a helper method to define mock.On call
//  - ctx context.Context
//  - in *photomanager.GetPhotosByGameIDRequest
//  - opts ...grpc.CallOption
func (_e *PhotographerServiceClient_Expecter) GetPhotosByGameID(ctx interface{}, in interface{}, opts ...interface{}) *PhotographerServiceClient_GetPhotosByGameID_Call {
	return &PhotographerServiceClient_GetPhotosByGameID_Call{Call: _e.mock.On("GetPhotosByGameID",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *PhotographerServiceClient_GetPhotosByGameID_Call) Run(run func(ctx context.Context, in *photomanager.GetPhotosByGameIDRequest, opts ...grpc.CallOption)) *PhotographerServiceClient_GetPhotosByGameID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*photomanager.GetPhotosByGameIDRequest), variadicArgs...)
	})
	return _c
}

func (_c *PhotographerServiceClient_GetPhotosByGameID_Call) Return(_a0 *photomanager.GetPhotosByGameIDResponse, _a1 error) *PhotographerServiceClient_GetPhotosByGameID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewPhotographerServiceClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewPhotographerServiceClient creates a new instance of PhotographerServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPhotographerServiceClient(t mockConstructorTestingTNewPhotographerServiceClient) *PhotographerServiceClient {
	mock := &PhotographerServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
